version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: easy-travels-api-db
    ports:
      - "5432:5432"
    environment:
      - PG_DATABASE=${PG_DATABASE}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
